name: prettier-java-action
description: 'Format java code with prettier'
inputs:
  prettier-args:
    description: 'Arguments for Prettier cli.'
    required: true
    default: "-w"
runs:
  using: node16
  main: 'build/index.js'
